<?php

use Magento\Catalog\Model\Product\Attribute\Source\Status;
use Magento\Catalog\Model\Product\Type;
use Magento\Catalog\Model\Product\Visibility;

$productDetails = [
    [
        'id'                => 1,
        'attributeSetId'    => 4,
        'name'              => 'T-shirt with crochet detail',
        'sku'               => 't_shirt_with_crochet_detail',
        'price'             => 17.95,
        'special_price'     => 10.95,
        'visibility'        => Visibility::VISIBILITY_BOTH,
        'status'            => Status::STATUS_ENABLED,
        'type'              => Type::TYPE_SIMPLE,
        'websiteIds'        => [1],
        'stockData'         =>
            [
                'qty' => 10000,
                'is_in_stock' => 1
            ],
        'image'             => '/a/b/abasicimage.jpg',
        'description'       => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight'            => 1,
        'short_description' => 'Length approx 59cm.'
    ],
    [
        'id'                => 2,
        'attributeSetId'    => 4,
        'name'              => 'Glitzy vest top with trim',
        'sku'               => 'glitzy_vest_top_with_trim',
        'price'             => 19.95,
        'visibility'        => Visibility::VISIBILITY_BOTH,
        'status'            => Status::STATUS_ENABLED,
        'type'              => Type::TYPE_SIMPLE,
        'websiteIds'        => [1],
        'stockData'         =>
            [
                'qty' => 10000,
                'is_in_stock' => 1
            ],
        'image'             => '/a/b/abasicimage.jpg',
        'description'       => 'Sleeveless top withnecklace featuring cauri shell shapes. Top has an intriguing glitzy finish in a crushed waffle effect. Straight shape. Round neckline. Unfinished lower edge. 3-strand removable necklace, to attach with metal fastener.',
        'weight'            => 1,
        'short_description' => 'Length approx 61cm (shoulder to hem). 100% polyester.'
    ],
    [
        'id' => 110,
        'attributeSetId' => 4,
        'name' => 'Simple Product 110',
        'sku' => 'simple_product_110',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 111,
        'attributeSetId' => 4,
        'name' => 'Simple Product 111',
        'sku' => 'simple_product_111',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 112,
        'attributeSetId' => 4,
        'name' => 'Simple Product 112',
        'sku' => 'simple_product_112',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 113,
        'attributeSetId' => 4,
        'name' => 'Simple Product 113',
        'sku' => 'simple_product_113',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 114,
        'attributeSetId' => 4,
        'name' => 'Simple Product 114',
        'sku' => 'simple_product_114',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 115,
        'attributeSetId' => 4,
        'name' => 'Simple Product 115',
        'sku' => 'simple_product_115',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 116,
        'attributeSetId' => 4,
        'name' => 'Simple Product 116',
        'sku' => 'simple_product_116',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 117,
        'attributeSetId' => 4,
        'name' => 'Simple Product 117',
        'sku' => 'simple_product_117',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 118,
        'attributeSetId' => 4,
        'name' => 'Simple Product 118',
        'sku' => 'simple_product_118',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 119,
        'attributeSetId' => 4,
        'name' => 'Simple Product 119',
        'sku' => 'simple_product_119',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 120,
        'attributeSetId' => 4,
        'name' => 'Simple Product 120',
        'sku' => 'simple_product_120',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 121,
        'attributeSetId' => 4,
        'name' => 'Simple Product 121',
        'sku' => 'simple_product_121',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 122,
        'attributeSetId' => 4,
        'name' => 'Simple Product 122',
        'sku' => 'simple_product_122',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 123,
        'attributeSetId' => 4,
        'name' => 'Simple Product 123',
        'sku' => 'simple_product_123',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 124,
        'attributeSetId' => 4,
        'name' => 'Simple Product 124',
        'sku' => 'simple_product_124',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 125,
        'attributeSetId' => 4,
        'name' => 'Simple Product 125',
        'sku' => 'simple_product_125',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 126,
        'attributeSetId' => 4,
        'name' => 'Simple Product 126',
        'sku' => 'simple_product_126',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 127,
        'attributeSetId' => 4,
        'name' => 'Simple Product 127',
        'sku' => 'simple_product_127',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 128,
        'attributeSetId' => 4,
        'name' => 'Simple Product 128',
        'sku' => 'simple_product_128',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 129,
        'attributeSetId' => 4,
        'name' => 'Simple Product 129',
        'sku' => 'simple_product_129',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 130,
        'attributeSetId' => 4,
        'name' => 'Simple Product 130',
        'sku' => 'simple_product_130',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 131,
        'attributeSetId' => 4,
        'name' => 'Simple Product 131',
        'sku' => 'simple_product_131',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 132,
        'attributeSetId' => 4,
        'name' => 'Simple Product 132',
        'sku' => 'simple_product_132',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 133,
        'attributeSetId' => 4,
        'name' => 'Simple Product 133',
        'sku' => 'simple_product_133',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 134,
        'attributeSetId' => 4,
        'name' => 'Simple Product 134',
        'sku' => 'simple_product_134',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 135,
        'attributeSetId' => 4,
        'name' => 'Simple Product 135',
        'sku' => 'simple_product_135',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 136,
        'attributeSetId' => 4,
        'name' => 'Simple Product 136',
        'sku' => 'simple_product_136',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 137,
        'attributeSetId' => 4,
        'name' => 'Simple Product 137',
        'sku' => 'simple_product_137',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 138,
        'attributeSetId' => 4,
        'name' => 'Simple Product 138',
        'sku' => 'simple_product_138',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 139,
        'attributeSetId' => 4,
        'name' => 'Simple Product 139',
        'sku' => 'simple_product_139',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 140,
        'attributeSetId' => 4,
        'name' => 'Simple Product 140',
        'sku' => 'simple_product_140',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 141,
        'attributeSetId' => 4,
        'name' => 'Simple Product 141',
        'sku' => 'simple_product_141',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 142,
        'attributeSetId' => 4,
        'name' => 'Simple Product 142',
        'sku' => 'simple_product_142',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 143,
        'attributeSetId' => 4,
        'name' => 'Simple Product 143',
        'sku' => 'simple_product_143',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 144,
        'attributeSetId' => 4,
        'name' => 'Simple Product 144',
        'sku' => 'simple_product_144',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 145,
        'attributeSetId' => 4,
        'name' => 'Simple Product 145',
        'sku' => 'simple_product_145',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 146,
        'attributeSetId' => 4,
        'name' => 'Simple Product 146',
        'sku' => 'simple_product_146',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 147,
        'attributeSetId' => 4,
        'name' => 'Simple Product 147',
        'sku' => 'simple_product_147',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 148,
        'attributeSetId' => 4,
        'name' => 'Simple Product 148',
        'sku' => 'simple_product_148',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 149,
        'attributeSetId' => 4,
        'name' => 'Simple Product 149',
        'sku' => 'simple_product_149',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 150,
        'attributeSetId' => 4,
        'name' => 'Simple Product 150',
        'sku' => 'simple_product_150',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 151,
        'attributeSetId' => 4,
        'name' => 'Simple Product 151',
        'sku' => 'simple_product_151',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 152,
        'attributeSetId' => 4,
        'name' => 'Simple Product 152',
        'sku' => 'simple_product_152',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 153,
        'attributeSetId' => 4,
        'name' => 'Simple Product 153',
        'sku' => 'simple_product_153',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 154,
        'attributeSetId' => 4,
        'name' => 'Simple Product 154',
        'sku' => 'simple_product_154',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 155,
        'attributeSetId' => 4,
        'name' => 'Simple Product 155',
        'sku' => 'simple_product_155',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 156,
        'attributeSetId' => 4,
        'name' => 'Simple Product 156',
        'sku' => 'simple_product_156',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 157,
        'attributeSetId' => 4,
        'name' => 'Simple Product 157',
        'sku' => 'simple_product_157',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 158,
        'attributeSetId' => 4,
        'name' => 'Simple Product 158',
        'sku' => 'simple_product_158',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 159,
        'attributeSetId' => 4,
        'name' => 'Simple Product 159',
        'sku' => 'simple_product_159',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 160,
        'attributeSetId' => 4,
        'name' => 'Simple Product 160',
        'sku' => 'simple_product_160',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 161,
        'attributeSetId' => 4,
        'name' => 'Simple Product 161',
        'sku' => 'simple_product_161',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 162,
        'attributeSetId' => 4,
        'name' => 'Simple Product 162',
        'sku' => 'simple_product_162',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 163,
        'attributeSetId' => 4,
        'name' => 'Simple Product 163',
        'sku' => 'simple_product_163',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 164,
        'attributeSetId' => 4,
        'name' => 'Simple Product 164',
        'sku' => 'simple_product_164',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 165,
        'attributeSetId' => 4,
        'name' => 'Simple Product 165',
        'sku' => 'simple_product_165',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 166,
        'attributeSetId' => 4,
        'name' => 'Simple Product 166',
        'sku' => 'simple_product_166',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 167,
        'attributeSetId' => 4,
        'name' => 'Simple Product 167',
        'sku' => 'simple_product_167',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 168,
        'attributeSetId' => 4,
        'name' => 'Simple Product 168',
        'sku' => 'simple_product_168',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 169,
        'attributeSetId' => 4,
        'name' => 'Simple Product 169',
        'sku' => 'simple_product_169',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 170,
        'attributeSetId' => 4,
        'name' => 'Simple Product 170',
        'sku' => 'simple_product_170',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 171,
        'attributeSetId' => 4,
        'name' => 'Simple Product 171',
        'sku' => 'simple_product_171',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 172,
        'attributeSetId' => 4,
        'name' => 'Simple Product 172',
        'sku' => 'simple_product_172',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 173,
        'attributeSetId' => 4,
        'name' => 'Simple Product 173',
        'sku' => 'simple_product_173',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 174,
        'attributeSetId' => 4,
        'name' => 'Simple Product 174',
        'sku' => 'simple_product_174',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 175,
        'attributeSetId' => 4,
        'name' => 'Simple Product 175',
        'sku' => 'simple_product_175',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 176,
        'attributeSetId' => 4,
        'name' => 'Simple Product 176',
        'sku' => 'simple_product_176',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 177,
        'attributeSetId' => 4,
        'name' => 'Simple Product 177',
        'sku' => 'simple_product_177',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 178,
        'attributeSetId' => 4,
        'name' => 'Simple Product 178',
        'sku' => 'simple_product_178',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 179,
        'attributeSetId' => 4,
        'name' => 'Simple Product 179',
        'sku' => 'simple_product_179',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 180,
        'attributeSetId' => 4,
        'name' => 'Simple Product 180',
        'sku' => 'simple_product_180',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 181,
        'attributeSetId' => 4,
        'name' => 'Simple Product 181',
        'sku' => 'simple_product_181',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 182,
        'attributeSetId' => 4,
        'name' => 'Simple Product 182',
        'sku' => 'simple_product_182',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 183,
        'attributeSetId' => 4,
        'name' => 'Simple Product 183',
        'sku' => 'simple_product_183',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 184,
        'attributeSetId' => 4,
        'name' => 'Simple Product 184',
        'sku' => 'simple_product_184',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 185,
        'attributeSetId' => 4,
        'name' => 'Simple Product 185',
        'sku' => 'simple_product_185',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 186,
        'attributeSetId' => 4,
        'name' => 'Simple Product 186',
        'sku' => 'simple_product_186',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 187,
        'attributeSetId' => 4,
        'name' => 'Simple Product 187',
        'sku' => 'simple_product_187',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 188,
        'attributeSetId' => 4,
        'name' => 'Simple Product 188',
        'sku' => 'simple_product_188',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 189,
        'attributeSetId' => 4,
        'name' => 'Simple Product 189',
        'sku' => 'simple_product_189',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 190,
        'attributeSetId' => 4,
        'name' => 'Simple Product 190',
        'sku' => 'simple_product_190',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 191,
        'attributeSetId' => 4,
        'name' => 'Simple Product 191',
        'sku' => 'simple_product_191',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 192,
        'attributeSetId' => 4,
        'name' => 'Simple Product 192',
        'sku' => 'simple_product_192',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 193,
        'attributeSetId' => 4,
        'name' => 'Simple Product 193',
        'sku' => 'simple_product_193',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 194,
        'attributeSetId' => 4,
        'name' => 'Simple Product 194',
        'sku' => 'simple_product_194',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 195,
        'attributeSetId' => 4,
        'name' => 'Simple Product 195',
        'sku' => 'simple_product_195',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 196,
        'attributeSetId' => 4,
        'name' => 'Simple Product 196',
        'sku' => 'simple_product_196',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 197,
        'attributeSetId' => 4,
        'name' => 'Simple Product 197',
        'sku' => 'simple_product_197',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 198,
        'attributeSetId' => 4,
        'name' => 'Simple Product 198',
        'sku' => 'simple_product_198',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 199,
        'attributeSetId' => 4,
        'name' => 'Simple Product 199',
        'sku' => 'simple_product_199',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 200,
        'attributeSetId' => 4,
        'name' => 'Simple Product 200',
        'sku' => 'simple_product_200',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 201,
        'attributeSetId' => 4,
        'name' => 'Simple Product 201',
        'sku' => 'simple_product_201',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 202,
        'attributeSetId' => 4,
        'name' => 'Simple Product 202',
        'sku' => 'simple_product_202',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 203,
        'attributeSetId' => 4,
        'name' => 'Simple Product 203',
        'sku' => 'simple_product_203',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 204,
        'attributeSetId' => 4,
        'name' => 'Simple Product 204',
        'sku' => 'simple_product_204',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 205,
        'attributeSetId' => 4,
        'name' => 'Simple Product 205',
        'sku' => 'simple_product_205',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 206,
        'attributeSetId' => 4,
        'name' => 'Simple Product 206',
        'sku' => 'simple_product_206',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 207,
        'attributeSetId' => 4,
        'name' => 'Simple Product 207',
        'sku' => 'simple_product_207',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 208,
        'attributeSetId' => 4,
        'name' => 'Simple Product 208',
        'sku' => 'simple_product_208',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
    [
        'id' => 209,
        'attributeSetId' => 4,
        'name' => 'Simple Product 209',
        'sku' => 'simple_product_209',
        'price' => 17.949999999999999,
        'visibility' => Visibility::VISIBILITY_BOTH,
        'status' => Status::STATUS_ENABLED,
        'type' => Type::TYPE_SIMPLE,
        'websiteIds' => [ 1 ],
        'stockData' =>
            [
                'qty' => 10000,
                'is_in_stock' => 1,
            ],
        'image' => '/a/b/abasicimage.jpg',
        'description' => 'Unicolour top with sheer crochet detail across the upper front. A subtle, feminine design. In a textured flame cotton mix. Straight shape. Wide round neckline. Short sleeves. Topstitched lower edge. Invest in a few colours of this charming top!',
        'weight' => 1,
        'short_description' => 'Length approx 59cm.',
    ],
];
